* #11: Added swagger.
exasol/exasol-rest-api pull request #17
Opened 2021-09-23 11:42 UTC by AnastasiiaSergienko

Closes #11

2021-09-23 12:19 UTC, AnastasiiaSergienko commented
This is a simple implementation where the swagger files were generated manually with `swag init` command. It can be possible to automate it in future, but maybe we start with something simple

2021-09-23 12:53 UTC, jakobbraun commented
> This is a simple implementation where the swagger files were generated manually with `swag init` command. It can be possible to automate it in future, but maybe we start with something simple

Adding it to the build should not be very much effort. There is a maven plugin for that: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-maven-plugin/README.md

If you don't want to do it in this PR, please create a ticket.

2021-09-23 13:05 UTC, jakobbraun requested changes

2021-09-23 13:05 UTC, jakobbraun commented on main.go
> +// @version 0.1.0
Different solution:
set version to something like `>>>project.version<<<`
replace this in the generated files by the project version from go file
(inspired from here: https://stackoverflow.com/questions/57821746/use-artifact-version-number-in-openapi-spec-definition)

2021-09-23 13:10 UTC, jakobbraun commented
add developer guide
add script for building doc

2021-09-24 07:43 UTC, jakobbraun requested changes

2021-09-24 07:43 UTC, jakobbraun commented on README.md
> +## Information for Developers
```suggestion
```

2021-09-24 10:33 UTC, jakobbraun approved these changes

2021-09-24 10:36 UTC, merged