Security/88 fix vulnerabilities
exasol/exasol-rest-api pull request #89
Opened 2024-02-06 15:48 UTC by pj-spoelders

Closes #88

2024-02-07 09:35 UTC, kaklakariada requested changes

2024-02-07 09:35 UTC, kaklakariada commented on go.mod
> +	github.com/swaggo/swag v1.16.3
Please update the `swag` version also in the other places (search for `1.16.2`) to ensure consistent behavior.

2024-02-07 10:44 UTC, pj-spoelders commented on doc/changes/changes_0.2.14.md
> +* github.com/containerd/containerd
Done

2024-02-08 03:40 UTC, kaklakariada requested changes

2024-02-08 03:40 UTC, kaklakariada commented on doc/changes/changes_0.2.14.md
Update release date

2024-02-08 09:26 UTC, merged